import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import UserWrapper from "@/app/ui/home/home";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jetlag Poznań",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <UserWrapper>{children}</UserWrapper>
          <footer>
            Inspired by <a href="https://nebula.tv/jetlag/">Jet Lag: The Game</a>
          </footer>
        </body>
      </UserProvider>
    </html>
  );
}
