import "@/app/globals.css";
import type { Metadata } from "next";
import { comfortaa } from "@/app/fonts";

export const metadata: Metadata = {
  title: "Jetlag Poznań",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>
        {children}
        <footer>
          Inspired by <a href="https://nebula.tv/jetlag/">Jet Lag: The Game</a>
        </footer>
      </body>
    </html>
  );
}
