import type { Metadata } from "next";
import "../globals.css";
import { Navigation } from "@/app/ui/navigation";
import { validateSession } from "@/app/api/auth";
import { db } from "@/app/api/db";
import React from "react";
import { comfortaa } from "@/app/fonts";

export const metadata: Metadata = {
  title: "Jetlag Poznań",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userId = await validateSession();
  const user = await db.user.findFirstOrThrow({
    where: {
      id: userId,
    },
  });

  return (
    <html lang="en">
      <body className={comfortaa.className}>
        <Navigation username={user.username} />
        {children}
        <footer>
          Inspired by <a href="https://nebula.tv/jetlag/">Jet Lag: The Game</a>
        </footer>
      </body>
    </html>
  );
}
